<?php

function html2pdf_menu(){
    $item['html2pdf'] = array(
        'type' => MENU_CALLBACK,
        'access callback' => 1,
        'page arguments' => array(1),
        'page callback' => '_html2pdf_menu_callback',
//        'delivery callback' => 'ajax_deliver',
    );
    return $item;
}


function my_exec($cmd, $input='',$htmltemp){
    $proc=proc_open($cmd, array(0=>array('pipe', 'r'), 1=>array('pipe', 'w'), 2=>array('pipe', 'w')), $pipes);
//    echo fwrite($pipes[0], $input);fclose($pipes[0]);
//    echo stream_get_contents($pipes[1])."\n<br/>";
//    fclose($pipes[1]);
//    echo stream_get_contents($pipes[2])."\n<br/>";
//    fclose($pipes[2]);
//    echo proc_close($proc);
//    
    $stdout=stream_get_contents($pipes[1]);fclose($pipes[1]);
    $stderr=stream_get_contents($pipes[2]);fclose($pipes[2]);
    $rtn=proc_close($proc);
    return array('stdout'=>$stdout,
                 'stderr'=>$stderr,
                 'return'=>$rtn
                      );
 }
// http://blog.dubbelboer.com/2012/08/24/execute-with-timeout.html
function exec_timeout($cmd, $timeout) {
  // File descriptors passed to the process.
  $descriptors = array(
    0 => array('pipe', 'r'),  // stdin
    1 => array('pipe', 'w'),  // stdout
    2 => array('pipe', 'w')   // stderr
  );

  // Start the process.
  $process = proc_open('exec ' . $cmd, $descriptors, $pipes);

  if (!is_resource($process)) {
    throw new \Exception('Could not execute process');
  }

  // Set the stdout stream to BLOCKING
  stream_set_blocking($pipes[1], 1);

  // Turn the timeout into microseconds.
  $timeout = $timeout * 1000000;

  // Output buffer.
  $buffer = '';

  // While we have time to wait.
  while ($timeout > 0) {
    $start = microtime(true);

    // Wait until we have output or the timer expired.
    $read  = array($pipes[1]);
    $other = array();
    stream_select($read, $other, $other, 0, $timeout);

    // Get the status of the process.
    // Do this before we read from the stream,
    // this way we can't lose the last bit of output if the process dies between these functions.
    $status = proc_get_status($process);

    // Read the contents from the buffer.
    // This function will always return immediately as the stream is none-blocking.
    $buffer .= stream_get_contents($pipes[1]);

    if (!$status['running']) {
      // Break from this loop if the process exited before the timeout.
      break;
    }

    // Subtract the number of microseconds that we waited.
    $timeout -= (microtime(true) - $start) * 1000000;
//    echo $timeout."<br/>\n";
  }

  // Check if there were any errors.
  $errors = stream_get_contents($pipes[2]);

  if (!empty($errors)) {
    throw new \Exception($errors);
  }

  // Kill the process in case the timeout expired and it's still running.
  // If the process already exited this won't do anything.
  proc_terminate($process, 9);

  // Close all streams.
  fclose($pipes[0]);
  fclose($pipes[1]);
  fclose($pipes[2]);

  proc_close($process);

  return $buffer;
}

function _html2pdf_menu_callback(){    
    $html2pdf =  drupal_get_path("module", "html2pdf");
    chdir(drupal_get_path("module", "html2pdf"));
    
    $cmd = 'phantomjs script.js '.$_GET["w"].' '.$_GET["h"];
    
    $output = exec_timeout($cmd, 1);
//    $output coming from :
//          $buffer .= stream_get_contents($pipes[1]);

// JSON OUTPUT / phantomjs direct output..
//    echo $output;
    
    
//  ##  HTML output
echo    '<html><head></head><body><img src="'.$html2pdf.'/out.png?'.time().'"/>';
echo    '<script>    '.
        '   var status = '.$output.';       '.
        '   console.log(status);            '.
        '   window.location = "'.$html2pdf.'/out.pdf";          '.
        '//  document.title = status.success;'.
        '</script>';
echo    '</body></html>';
    
//  done !
    die();
}

//echo date(DATE_W3C)."\n";
//echo json_encode(my_exec($cmd,'',$htmltemp));

//echo date(DATE_W3C)."\n";
//$out = 0;
//echo passthru($cmd, $out);
//echo $out;
//exhit();
//var_export(my_exec("wkhtmltopdf --page-width 350 --page-height 235 /var/www/s/htmltemp.html  /var/www/s/wkoutput.pdf "));

//$htmltemp = $_SERVER["DOCUMENT_ROOT"].'/'.drupal_get_path("module", "html2pdf").'/out/out.html';
//$pdf = $_SERVER["DOCUMENT_ROOT"].'/'.drupal_get_path("module", "html2pdf").'/out/out.pdf';
//$handle = fopen($htmltemp , 'w');
//$h = 500;
//$w = 500;
//$output = array();
//$return_var = 0;
//fwrite($handle, '
//<html><body>
//    <div id="layerContainer"    style="        height: '.$h.';        width:'.$w.';">'.
//        REQUEST_TIME.'</div>
//</body></html>');

//$cmd = 'cd '.$html2pdf.';';

//function html2pdf(){
//    
//}
//function html2pdf(){
//    
//}
