<?php
function html2pdf_menu(){
    $item['html2pdf'] = array(
        'type' => MENU_CALLBACK,
        'access callback' => 1,
        'page arguments' => array(1),
        'page callback' => '_html2pdf_menu_callback',
//        'delivery callback' => 'ajax_deliver',
    );
    return $item;
}
function html2pdf_preprocess_node($node){
        $arg =arg();
        if($node["type"] === "birthday"){
            drupal_add_js(drupal_get_path("module", "html2pdf").'/js/html2pdf.js');
            
        }
}
function exec_timeout($cmd, $timeout) {
// adapted from http://blog.dubbelboer.com/2012/08/24/execute-with-timeout.html

// File descriptors passed to the process.
  $descriptors = array(
    0 => array('pipe', 'r'),  // stdin
    1 => array('pipe', 'w'),  // stdout
    2 => array('pipe', 'w')   // stderr
  );

  // Start the process.
  $process = proc_open('exec ' . $cmd, $descriptors, $pipes);

  if (!is_resource($process)) {
    throw new \Exception('Could not execute process');
  }

  // Set the stdout stream to BLOCKING
  stream_set_blocking($pipes[1], 1);

  // Turn the timeout into microseconds.
  $timeout = $timeout * 1000000;

  // Output buffer.
  $buffer = '';

  // While we have time to wait.
  while ($timeout > 0) {
    $start = microtime(true);

    // Wait until we have output or the timer expired.
    $read  = array($pipes[1]);
    $other = array();
    stream_select($read, $other, $other, 0, $timeout);

    // Get the status of the process.
    // Do this before we read from the stream,
    // this way we can't lose the last bit of output if the process dies between these functions.
    $status = proc_get_status($process);

    // Read the contents from the buffer.
    // This function will always return immediately as the stream is none-blocking.
    $buffer .= stream_get_contents($pipes[1]);

    if (!$status['running']) {
      // Break from this loop if the process exited before the timeout.
      break;
    }

    // Subtract the number of microseconds that we waited.
    $timeout -= (microtime(true) - $start) * 1000000;
//    echo $timeout."<br/>\n";
  }

  // Check if there were any errors.
  $errors = stream_get_contents($pipes[2]);

  if (!empty($errors)) {
    throw new \Exception($errors);
  }

  // Kill the process in case the timeout expired and it's still running.
  // If the process already exited this won't do anything.
  proc_terminate($process, 9);

  // Close all streams.
  fclose($pipes[0]);
  fclose($pipes[1]);
  fclose($pipes[2]);

  proc_close($process);

  return $buffer;
}
function _html2pdf_menu_callback(){    
    $html2pdf =  drupal_get_path("module", "html2pdf");
    chdir( $html2pdf );
    $container = (object)$_POST["container"];
    $post = json_encode($container ,  JSON_FORCE_OBJECT);
    $cmd = "phantomjs script.js '".$post."'";
    $output = exec_timeout($cmd, 1);
//    $output <=  $buffer .= stream_get_contents($pipes[1]);

//  ##  JSON OUTPUT / phantomjs direct output..
//echo $output;

//  ##F ILE OUTPUT
if (file_exists($file)) {
    header('Content-Description: File Transfer');
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename='.basename($file));
    header('Content-Transfer-Encoding: binary');
    header('Expires: 0');
    header('Cache-Control: must-revalidate');
    header('Pragma: public');
    header('Content-Length: ' . filesize($file));
    ob_clean();
    flush();
    readfile($file);
    exit;
}

//  ##  HTML output
//echo    '<html><head></head><body><img src="'.$html2pdf.'/out.png?'.time().'"/>';
//echo    '<script>    '.
//        '   var status = '.$output.';       '.
//        '   console.log(status);            '.
//        '   window.location = "'.$html2pdf.'/out.pdf";          '.
//        '//  document.title = status.success;'.
//        '</script>';
//echo    '</body></html>';    
//  done !
    die();
}